import React from 'react'

import type { Metadata } from 'next'

interface Props {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({children}: Props) =>  {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}

export default RootLayout